### ISSUE TITLE
must be of type Pin, not int

### ISSUE THREAD

**Issue by vladbondarenko** [ehong-tl/micropySX126X#15]
Hello,

When using TX from examples i got this:

Traceback (most recent call last):
  File "<stdin>", line 8, in <module>
  File "/lib/sx1262.py", line 20, in __init__
  File "/lib/sx126x.py", line 53, in __init__
TypeError: clock must be of type Pin, not int

Any ideas how to fix?

Thanks.

**Comment by ehong-tl** [comment]
Hi,

For Circuitpython, all the pins variable in the constructor must be Pin object instead of int.
