### ISSUE TITLE
memory allocation failed

### ISSUE THREAD

**Issue by kekemuyu** [ehong-tl/micropySX126X#2]
board:    Generic ESP32 module

run example/pingpon/device1/main.py ,log error info:

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "sx1262.py", line 2, in <module>
MemoryError: memory allocation failed, allocating 704 bytes`

**Comment by ehong-tl** [comment]
May I know which ESP32 module you are using? It could be your module comes with less RAM.

Or you can try to freeze the code into firmware to mitigate this issue.

**Comment by kekemuyu** [comment]
esp32-wroom-32 and esp32-pico-kit are both have the same error.Later,I will try to compile to firmware.Thanks your hard work.
