### ISSUE TITLE
Memory allocation problem with Raspberry pico w

### ISSUE THREAD

**Issue by Patxi080** [ehong-tl/micropySX126X#27]
I wanted to use the library in a project but when when the library sx1262 is imported this error happens:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/sx1262.py", line 2, in <module>
MemoryError: memory allocation failed, allocating 176 byte
```
I created a new file to check if it was the library with only:
`import sx1262`
And it keeps happening.
Here is an image:
![image](https://github.com/ehong-tl/micropySX126X/assets/75630204/09197d03-102f-4d61-817f-d31c62c565e6)

**Comment by ehong-tl** [comment]
Hi,

This could be due to insufficient RAM in Pico W than in standard Pico.

One thing you can try is to compile the library into .mpy bytecode.

Sorry that I can't give you a complete solution as I have no experience in using Pico / Pico W.

**Comment by Ruben0595** [comment]
[sx1262_mpy_lib.zip](https://github.com/user-attachments/files/15605522/sx1262_mpy_lib.zip)

Here are mpy files of the library. just replace the current sx1262/126x .py files with these and should work fine.
